### ISSUE TITLE
millify is not a function

### ISSUE THREAD

**Issue by L0SER8228** [izolate/millify#22]
I'm using this in a discord bot.
 My code is below 
```js
const millify = require("millify");

    const views = millify(npsong.views);
    const like = millify(npsong.likes);
    const lislikes = millify(npsong.dislikes);
```
I'm getting the error `millify is not a function`

**Comment by izolate** [comment]
Hi. Unfortunately, supporting both CommonJS (CJS) and ES Modules (ESM) in one package is tricky because they're incompatible. I'm researching better ways to support both, but for now you can use the workaround syntax for CJS:

```js
const { default: millify } = require("millify");
```

Let me know if this works for you. Thanks!

**Comment by izolate** [comment]
@L0SER8228 as of v3.4.0 you can now use the following syntax:

```
import { millify } from "millify";
```

Please re-open if you need.

**Comment by L0SER8228** [comment]
Sadly, this is not working.
I was using the below code on v3.3.0 and that was working properly. But now any method is not working on v3.4.0
```js
const millify = require("millify");

    const views = millify.default(npsong.views);
    const like = millify.default(npsong.likes);
    const lislikes = millify.default(npsong.dislikes);
```

**Comment by L0SER8228** [comment]
I've no problem with using a `default` word extra🙂

**Comment by izolate** [comment]
@L0SER8228 Please change your code to this:

```js
const { millify } = require("millify");

const views = millify(npsong.views);
const like = millify(npsong.likes);
const lislikes = millify(npsong.dislikes);
```

Let me know if this works for you.

**Comment by L0SER8228** [comment]
> Sadly, this is not working.
> I was using the below code on v3.3.0 and that was working properly. But now any method is not working on v3.4.0
> 
> ```js
> const millify = require("millify");
> 
>     const views = millify.default(npsong.views);
>     const like = millify.default(npsong.likes);
>     const lislikes = millify.default(npsong.dislikes);
> ```

any method is not working on v3.4.0 for me

**Comment by izolate** [comment]
> > Sadly, this is not working.
> 
> > I was using the below code on v3.3.0 and that was working properly. But now any method is not working on v3.4.0
> 
> > 
> 
> > ```js
> 
> > const millify = require("millify");
> 
> > 
> 
> >     const views = millify.default(npsong.views);
> 
> >     const like = millify.default(npsong.likes);
> 
> >     const lislikes = millify.default(npsong.dislikes);
> 
> > ```
> 
> 
> 
> any method is not working on v3.4.0 for me

I've verified the code I shared is working with v3.4.0, so if that doesn't work for you, you'll need to provide more info for me to help you. What node version are you using?

**Comment by L0SER8228** [comment]
"node": "14.x"
    "discord.js": "^12.5.1",

**Comment by izolate** [comment]
> @L0SER8228 Please change your code to this:
> 
> ```js
> const { millify } = require("millify"); // v3.4.0
> 
> const views = millify(npsong.views);
> const like = millify(npsong.likes);
> const lislikes = millify(npsong.dislikes);
> ```
> 
> Let me know if this works for you.

@L0SER8228 I've verified this does indeed work in Node 14, so the problem must be in your codebase. Check if your code matches what I suggested (no default needed).

**Comment by L0SER8228** [comment]
Yea, thanks for the update. Now everything is working perfectly. No `default` needs

**Comment by matthewmayer** [comment]
Please use semver-major version number changes if you change the way the library needs to be imported! This broke my code again :(

**Comment by izolate** [comment]
My sincere apologies @matthewmayer! I thought it was backwards compatible, but evidently not.

I've just pushed v3.5.0 with the change to default export reverted back to how it was in v3.3.0. This should prevent others from facing the same issue.

Thanks for reporting, please let me know if you have any further trouble.

**Comment by matthewmayer** [comment]
Cool thanks it's an easy enough change so you could probably just push it again as 4.0.0 and add a note on the readme

**Comment by izolate** [comment]
I've opted for both a default and named export in v3.5, so both should technically work now.

However, I'll take a closer look at this project's structure later and make any further changes in 4.x.

Thanks again.

**Comment by deadcoder0904** [comment]
@izolate This should be in the README. The README is not using a named export. Please update it so someone else uses it correctly in the first try :)

**Comment by izolate** [comment]
@deadcoder0904 Thanks for bringing the README to my attention. Updated.
